#pragma once

#define SWAP_DESIRED_GL_VERSION_MAJOR 4
#if SWAP_PLATFORM_MACOS
#  define SWAP_DESIRED_GL_VERSION_MINOR 1
#else
#  define SWAP_DESIRED_GL_VERSION_MINOR 6
#endif

#define SWAP_GL_OBJECT_LABEL_SUPPORTED (SWAP_DESIRED_GL_VERSION_MAJOR > 4 || (SWAP_DESIRED_GL_VERSION_MAJOR == 4 && SWAP_DESIRED_GL_VERSION_MINOR >= 3))
